# Generated by Django 5.2.8 on 2025-11-17 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense_manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='transaction_type',
            field=models.CharField(blank=True, max_length=10, verbose_name='Transaction Type'),
        ),
    ]
