# Generated by Django 5.2.8 on 2025-11-20 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense_manager', '0003_bankaccount_expense_bank_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankaccount',
            name='balance',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True, verbose_name='Balance'),
        ),
    ]
